// This file will be auto-generated by Supabase CLI
// Run: npm run supabase:gen-types (for local) or npm run supabase:gen-types-remote (for remote)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      // Tables will be generated here by Supabase CLI
      [key: string]: {
        Row: Record<string, never>
        Insert: Record<string, never>
        Update: Record<string, never>
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Common types for the journal application
export interface Paper {
  id: string
  title: string
  abstract: string
  authors: string[]
  keywords: string[]
  doi?: string
  published_at: string
  created_at: string
  updated_at: string
  status: 'draft' | 'under_review' | 'accepted' | 'rejected' | 'published'
  volume?: number
  issue?: number
  pages?: string
  pdf_url?: string
}

export interface Author {
  id: string
  name: string
  email: string
  affiliation: string
  orcid?: string
  bio?: string
  created_at: string
  updated_at: string
}

export interface Review {
  id: string
  paper_id: string
  reviewer_id: string
  rating: number
  comments: string
  recommendation: 'accept' | 'reject' | 'revise'
  created_at: string
  updated_at: string
}

export interface User {
  id: string
  email: string
  full_name?: string
  role: 'author' | 'reviewer' | 'editor' | 'admin'
  created_at: string
  updated_at: string
}